### PR TITLE
add get_interfaces_ip

### PR DESCRIPTION
**Pull request by chrisbnorman**
adding get ip interface output for vrf all

### CODE REVIEW

**Review by samerd — CHANGES_REQUESTED** [review]
@chrisbnorman :
please add unit-tests for the new API.
this will fix the CI failure

**Review by samerd — CHANGES_REQUESTED** [review]
@chrisbnorman 
Thanks for your contributions, it is really appreciated.
However, please follow these guidance.
1- One API function per commit.
2- You should add unit-test for each added function.
I cannot approve your commits otherwise.

**Comment by chrisbnorman** [comment]
understand lets close this pull request for now, not quite sure how to do the unit test right now. ill do a new one once ive worked it out!

**Comment by samerd** [comment]
@chrisbnorman :
please see this commit:
https://github.com/napalm-automation-community/napalm-onyx/pull/2/commits/6b1d6d782f87ec1c0b42fc7d1b035072ffa1508f
it contains some tests.

**Pull request closed without merging**
