### PR TITLE
support get_config in napalm and add test cases

### PR DESCRIPTION
**Pull request by anas-shami**
Add new function to napalm to get running and initial configuration from the switch with candidate config (if found.)

### CODE REVIEW

**Comment by anas-shami** [comment]
@samerd  @anasbadaha  it mays need .travis.yml change could I do this change?

**Comment by anas-shami** [comment]
@samerd could u please approve this?

**Comment by anas-shami** [comment]
finally, it passes tests, please review.

**Comment by samerd** [comment]
Thanks @anas-shami

**Pull request merged**
